config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :pagamentos
  resources :faturas
  resources :trabalhos
  resources :projetos
  resources :moedas
  resources :clientes
  resources :tarefas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
	belongs_to:projeto
	belongs_to:tarefa
end

app/controllers/trabalhos_controller.rb
class TrabalhosController < ApplicationController
  before_action :set_trabalho, only: [:show, :edit, :update, :destroy]

  # GET /trabalhos
  # GET /trabalhos.json
  def index
    @trabalhos = Trabalho.all
  end

  # GET /trabalhos/1
  # GET /trabalhos/1.json
  def show
  end

  # GET /trabalhos/new
  def new
    @trabalho = Trabalho.new
  end

  # GET /trabalhos/1/edit
  def edit
  end

  # POST /trabalhos
  # POST /trabalhos.json
  def create
    @trabalho = Trabalho.new(trabalho_params)

    respond_to do |format|
      if @trabalho.save
        format.html { redirect_to @trabalho, notice: 'Trabalho was successfully created.' }
        format.json { render :show, status: :created, location: @trabalho }
      else
        format.html { render :new }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabalhos/1
  # PATCH/PUT /trabalhos/1.json
  def update
    respond_to do |format|
      if @trabalho.update(trabalho_params)
        format.html { redirect_to @trabalho, notice: 'Trabalho was successfully updated.' }
        format.json { render :show, status: :ok, location: @trabalho }
      else
        format.html { render :edit }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabalhos/1
  # DELETE /trabalhos/1.json
  def destroy
    @trabalho.destroy
    respond_to do |format|
      format.html { redirect_to trabalhos_url, notice: 'Trabalho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabalho
      @trabalho = Trabalho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabalho_params
      params.require(:trabalho).permit(:projeto_id, :tarefa_id, :inicio, :final, :notas, :horas, :rendimento, :livre, :faturado)
    end
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/views/trabalhos/_form.html.erb
<%= form_with(model: trabalho, local: true) do |form| %>
  <% if trabalho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trabalho.errors.count, "error") %> prohibited this trabalho from being saved:</h2>

      <ul>
      <% trabalho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :projeto %>
    <%= collection_select(:trabalho, :projeto_id, Projeto.all, :id, :nome) %>
  </div>

  <div class="field">
    <%= form.label :tarefa %>
    <%= collection_select(:trabalho, :tarefa_id, Tarefa.all, :id, :nome) %>
  </div>

  <div class="field">
    <%= form.label :inicio %>
    <%= form.datetime_select :inicio %>
  </div>

  <div class="field">
    <%= form.label :final %>
    <%= form.datetime_select :final %>
  </div>

  <div class="field">
    <%= form.label :notas %>
    <%= form.text_field :notas %>
  </div>

  <div class="field">
    <%= form.label :horas %>
    <%= form.text_field :horas %>
  </div>

  <div class="field">
    <%= form.label :rendimento %>
    <%= form.text_field :rendimento %>
  </div>

  <div class="field">
    <%= form.label :livre %>
    <%= form.check_box :livre %>
  </div>

  <div class="field">
    <%= form.label :faturado %>
    <%= form.check_box :faturado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trabalhos/edit.html.erb
<h1>Editing Trabalho</h1>

<%= render 'form', trabalho: @trabalho %>

<%= link_to 'Show', @trabalho %> |
<%= link_to 'Back', trabalhos_path %>

app/views/trabalhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trabalhos</h1>

<table>
  <thead>
    <tr>
      <th>Inicio</th>
      <th>Final</th>
      <th>Horas</th>
      <th>Rendimento</th>
      <th>Livre</th>
      <th>Faturado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trabalhos.each do |trabalho| %>
      <tr>
        <td><%= trabalho.inicio %></td>
        <td><%= trabalho.final %></td>
        <td><%= trabalho.horas %></td>
        <td><%= trabalho.rendimento %></td>
        <td><%= trabalho.livre %></td>
        <td><%= trabalho.faturado %></td>
        <td><%= link_to 'Show', trabalho %></td>
        <td><%= link_to 'Edit', edit_trabalho_path(trabalho) %></td>
        <td><%= link_to 'Destroy', trabalho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trabalho', new_trabalho_path %>

app/views/trabalhos/new.html.erb
<h1>New Trabalho</h1>

<%= render 'form', trabalho: @trabalho %>

<%= link_to 'Back', trabalhos_path %>

app/views/trabalhos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inicio:</strong>
  <%= @trabalho.inicio %>
</p>

<p>
  <strong>Final:</strong>
  <%= @trabalho.final %>
</p>

<p>
  <strong>Notas:</strong>
  <%= @trabalho.notas %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @trabalho.horas %>
</p>

<p>
  <strong>Rendimento:</strong>
  <%= @trabalho.rendimento %>
</p>

<p>
  <strong>Livre:</strong>
  <%= @trabalho.livre %>
</p>

<p>
  <strong>Faturado:</strong>
  <%= @trabalho.faturado %>
</p>

<%= link_to 'Edit', edit_trabalho_path(@trabalho) %> |
<%= link_to 'Back', trabalhos_path %>